#!/usr/bin/env python3
"""Materialize variant dotenv inputs as private xcconfig build inputs.

Values are deliberately opaque: this script checks presence only, never trims,
classifies, interpolates, executes, or prints a supplied value.
"""

from __future__ import annotations

import argparse
import importlib
import os
import re
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path

try:
    dotenv_values = importlib.import_module("dotenv").dotenv_values
except ImportError:  # pragma: no cover - exercised by the toolchain preflight
    dotenv_values = None

VARIANTS = {
    "development": (".env.development", "Development.xcconfig"),
    "production": (".env.production", "Production.xcconfig"),
}
REQUIRED_KEYS = ("DEVELOPMENT_TEAM", "NHOST_SUBDOMAIN", "NHOST_REGION")
OUTPUT_KEYS = {
    "DEVELOPMENT_TEAM": "DEVELOPMENT_TEAM",
    "NHOST_SUBDOMAIN": "NEOGYM_NHOST_SUBDOMAIN",
    "NHOST_REGION": "NEOGYM_NHOST_REGION",
}
UNEXPANDED_PATTERN = re.compile(r"\$\([^)]*\)|\$\{[^}]*\}")


class ConfigError(RuntimeError):
    """A key-only configuration failure safe to surface in build logs."""


def load_dotenv(path: Path) -> dict[str, str]:
    if dotenv_values is None:
        raise ConfigError("python-dotenv is unavailable; run through the Nix devshell")
    if not path.is_file():
        raise ConfigError(f"missing dotenv file: {path.name}")

    parsed = dotenv_values(path, interpolate=False)
    values: dict[str, str] = {}
    failures: list[str] = []
    for key in REQUIRED_KEYS:
        value = parsed.get(key)
        if value is None:
            failures.append(f"missing key: {key}")
        elif value == "":
            failures.append(f"empty key: {key}")
        else:
            values[key] = value
    if failures:
        raise ConfigError("; ".join(failures))
    return values


def escape_xcconfig(value: str) -> str:
    """Escape an opaque value without allowing xcconfig comments or expansion.

    Xcode retains quotes and backslashes in custom build settings. Empty-setting
    expansions therefore bracket the value so leading/trailing spaces become
    interior, and separate adjacent slashes before Xcode's comment lexer sees
    them. Supplied punctuation otherwise remains literal and inert.
    """

    empty = "$(NEOGYM_XCCONFIG_EMPTY)"
    escaped = value.replace("//", f"/{empty}/")
    return empty + escaped + empty


def unescape_xcconfig(value: str) -> str:
    if value == "":
        raise ValueError("not a materialized value")
    empty = "$(NEOGYM_XCCONFIG_EMPTY)"
    if not value.startswith(empty) or not value.endswith(empty):
        raise ValueError("not a materialized value")
    body = value.removeprefix(empty).removesuffix(empty)
    return body.replace(f"/{empty}/", "//")


def render_xcconfig(values: Mapping[str, str]) -> str:
    lines = [
        "// Generated by Scripts/materialize-config.py. Do not commit.",
        "NEOGYM_XCCONFIG_EMPTY =",
    ]
    for dotenv_key in REQUIRED_KEYS:
        lines.append(
            f"{OUTPUT_KEYS[dotenv_key]} = {escape_xcconfig(values[dotenv_key])}"
        )
    return "\n".join(lines) + "\n"


def atomic_write_private(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
        path.chmod(0o600)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def materialize(variant: str, env_dir: Path, output_dir: Path) -> Path:
    env_name, output_name = VARIANTS[variant]
    values = load_dotenv(env_dir / env_name)
    output = output_dir / output_name
    atomic_write_private(output, render_xcconfig(values))
    return output


def selected_variants(selection: str) -> tuple[str, ...]:
    return tuple(VARIANTS) if selection == "all" else (selection,)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("variant", choices=(*VARIANTS, "all"))
    parser.add_argument("--env-dir", type=Path, default=Path("fastlane"))
    parser.add_argument(
        "--output-dir", type=Path, default=Path("Configuration/Generated")
    )
    args = parser.parse_args(argv)

    try:
        for variant in selected_variants(args.variant):
            materialize(variant, args.env_dir, args.output_dir)
    except ConfigError as error:
        print(f"configuration error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
