#!/usr/bin/env python3
"""Validate private deployment inputs and materialize derived Xcode settings.

The dotenv grammar is intentionally smaller than shell/dotenv syntax. Diagnostics
name only known keys, line numbers, variants, and tracked paths; supplied values
are never printed.
"""

from __future__ import annotations

import argparse
import os
import re
import stat
import subprocess
import sys
import tempfile
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path

VARIANTS = {
    "development": (".env.development", "Development.xcconfig"),
    "production": (".env.production", "Production.xcconfig"),
}
REQUIRED_KEYS = (
    "DEVELOPMENT_TEAM",
    "BUNDLE_IDENTIFIER_BASE",
    "NHOST_SUBDOMAIN",
    "NHOST_REGION",
)
KNOWN_KEYS = frozenset(REQUIRED_KEYS)
TEAM_PATTERN = re.compile(r"[A-Z0-9]{10}")
BUNDLE_LABEL_PATTERN = re.compile(r"[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?")
NHOST_VALUE_PATTERN = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?")


class ConfigError(RuntimeError):
    """A key-safe configuration failure suitable for logs."""


@dataclass(frozen=True)
class PrivateConfig:
    development_team: str
    bundle_identifier_base: str
    nhost_subdomain: str
    nhost_region: str

    def derived_settings(self) -> dict[str, str]:
        base = self.bundle_identifier_base
        return {
            "DEVELOPMENT_TEAM": self.development_team,
            "NEOGYM_APP_BUNDLE_IDENTIFIER": base,
            "NEOGYM_WIDGET_BUNDLE_IDENTIFIER": f"{base}.widgets",
            "NEOGYM_APP_GROUP_IDENTIFIER": f"group.{base}",
            "NEOGYM_KEYCHAIN_ACCESS_GROUP_SUFFIX": f"{base}.shared",
            "NEOGYM_NHOST_SUBDOMAIN": self.nhost_subdomain,
            "NEOGYM_NHOST_REGION": self.nhost_region,
        }


def _validate_value(key: str, value: str) -> None:
    if value == "":
        raise ConfigError(f"empty key: {key}")
    if key == "DEVELOPMENT_TEAM":
        valid = TEAM_PATTERN.fullmatch(value) is not None
    elif key == "BUNDLE_IDENTIFIER_BASE":
        labels = value.split(".")
        valid = (
            2 <= len(labels)
            and len(value) <= 255
            and all(BUNDLE_LABEL_PATTERN.fullmatch(label) for label in labels)
        )
    else:
        valid = NHOST_VALUE_PATTERN.fullmatch(value) is not None
    if not valid:
        raise ConfigError(f"malformed value for key: {key}")


def parse_dotenv(path: Path) -> PrivateConfig:
    if not path.is_file() or path.is_symlink():
        raise ConfigError(f"missing dotenv file: {path.name}")
    if stat.S_IMODE(path.stat().st_mode) != 0o600:
        raise ConfigError(f"dotenv file must have mode 0600: {path.name}")

    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError):
        raise ConfigError(f"unable to read dotenv file: {path.name}") from None

    values: dict[str, str] = {}
    for line_number, line in enumerate(lines, start=1):
        if line == "":
            continue
        if line.count("=") != 1:
            raise ConfigError(f"invalid dotenv syntax on line {line_number}")
        key, value = line.split("=", 1)
        if key not in KNOWN_KEYS:
            raise ConfigError(f"unknown key on line {line_number}")
        if key in values:
            raise ConfigError(f"duplicate key: {key}")
        _validate_value(key, value)
        values[key] = value

    missing = [key for key in REQUIRED_KEYS if key not in values]
    if missing:
        raise ConfigError("missing keys: " + ", ".join(missing))
    return PrivateConfig(
        development_team=values["DEVELOPMENT_TEAM"],
        bundle_identifier_base=values["BUNDLE_IDENTIFIER_BASE"],
        nhost_subdomain=values["NHOST_SUBDOMAIN"],
        nhost_region=values["NHOST_REGION"],
    )


def render_xcconfig(config: PrivateConfig) -> str:
    lines = ["// Generated by Scripts/materialize-config.py. Do not commit."]
    lines.extend(
        f"{key} = {value}" for key, value in config.derived_settings().items()
    )
    return "\n".join(lines) + "\n"


def atomic_write_private(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
        path.chmod(0o600)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def _selected_variants(selection: str) -> tuple[str, ...]:
    return tuple(VARIANTS) if selection == "all" else (selection,)


def load_private_configs(selection: str, env_dir: Path) -> dict[str, PrivateConfig]:
    selected = _selected_variants(selection)
    variants_to_validate = set(selected)
    for variant, (env_name, _) in VARIANTS.items():
        if (env_dir / env_name).exists():
            variants_to_validate.add(variant)

    configs: dict[str, PrivateConfig] = {}
    for variant in VARIANTS:
        if variant in variants_to_validate:
            env_name, _ = VARIANTS[variant]
            configs[variant] = parse_dotenv(env_dir / env_name)

    if len(configs) == 2:
        development = configs["development"].bundle_identifier_base
        production = configs["production"].bundle_identifier_base
        if development == production:
            raise ConfigError("development and production bundle bases must differ")
    return configs


def _audit_needles(configs: Mapping[str, PrivateConfig]) -> list[tuple[str, bytes]]:
    needles: list[tuple[str, bytes]] = []
    seen: set[bytes] = set()
    for config in configs.values():
        candidates = {
            "DEVELOPMENT_TEAM": config.development_team,
            "BUNDLE_IDENTIFIER_BASE": config.bundle_identifier_base,
            "NHOST_SUBDOMAIN": config.nhost_subdomain,
            "NHOST_REGION": config.nhost_region,
        }
        for key, value in candidates.items():
            if value == "local":
                continue
            encoded = value.encode("utf-8")
            if encoded not in seen:
                seen.add(encoded)
                needles.append((key, encoded))
    return needles


def _tracked_audit_paths(repo_root: Path) -> Iterable[Path]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=repo_root,
        check=False,
        capture_output=True,
    )
    if result.returncode != 0:
        raise ConfigError("tracked-value audit could not list tracked files")
    for raw_path in result.stdout.split(b"\0"):
        if not raw_path:
            continue
        try:
            relative = Path(os.fsdecode(raw_path))
        except UnicodeError:
            raise ConfigError("tracked-value audit found an invalid path") from None
        text = relative.as_posix()
        if (
            text in {"README.md", "CLAUDE.md", ".gitignore", "flake.nix"}
            or text.startswith("ios/NeoGym/")
            or text.startswith("nix/")
        ):
            yield relative


def audit_tracked_values(
    configs: Mapping[str, PrivateConfig], repo_root: Path
) -> None:
    needles = _audit_needles(configs)
    for relative in _tracked_audit_paths(repo_root):
        path = repo_root / relative
        if not path.exists():
            continue
        try:
            content = path.read_bytes()
        except OSError:
            raise ConfigError(f"tracked-value audit could not read: {relative}") from None
        for key, needle in needles:
            if needle in content:
                raise ConfigError(f"tracked-value audit found {key} in: {relative}")


def materialize(
    selection: str,
    env_dir: Path,
    output_dir: Path,
    *,
    audit_repo_root: Path | None = None,
) -> tuple[Path, ...]:
    configs = load_private_configs(selection, env_dir)
    if audit_repo_root is not None:
        audit_tracked_values(configs, audit_repo_root)

    outputs: list[Path] = []
    for variant in _selected_variants(selection):
        _, output_name = VARIANTS[variant]
        output = output_dir / output_name
        atomic_write_private(output, render_xcconfig(configs[variant]))
        outputs.append(output)
    return tuple(outputs)


def main(argv: list[str] | None = None) -> int:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("environment", choices=(*VARIANTS, "all"))
    parser.add_argument("--env-dir", type=Path, default=project_root)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=project_root / "Configuration" / "Generated",
    )
    args = parser.parse_args(argv)

    try:
        materialize(
            args.environment,
            args.env_dir,
            args.output_dir,
            audit_repo_root=project_root.parents[1],
        )
    except ConfigError as error:
        print(f"configuration error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
